[nexus]
NXOS-SW-1 ansible_host=192.168.1.19 peer_ip=192.168.1.13 src_ip=192.168.1.19
NXOS-SW-2 ansible_host=192.168.1.13 peer_ip=192.168.1.19 src_ip=192.168.1.13

[downstream]
SW-L3 ansible_host=192.168.1.21

[nexus:vars]
ansible_user=admin
ansible_password=admin
ansible_ssh_pass=admin
ansible_network_os=nxos
ansible_connection=network_cli
ansible_ssh_common_args='-o PubkeyAuthentication=no'

[downstream:vars]
ansible_user=admin
ansible_password=admin
ansible_ssh_pass=admin
ansible_network_os=ios
ansible_connection=network_cli
ansible_ssh_common_args='-o PubkeyAuthentication=no -o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa'
